# 以下为默认值，可以都不加，或者想改哪行加哪行(支持"云端配置服务"进行配置，支持写到"云端日志服务")
solon.logging.appender:
  console:
    level: INFO #可根据需要调整级别
    pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5level %magenta(${PID:-}) %white(---) %-20(%yellow([%20.20thread])) %-55(%cyan(%.32logger{30}:%L)) %msg%n"
  file:
    pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5level %magenta(${PID:-}) %white(---) %-20(%yellow([%20.20thread])) %-55(%cyan(%.32logger{30}:%L)) %msg%n"
    maxHistory: "7"
  cloud:
    level: INFO
#附件上传大小限制
server.request.maxFileSize: 500mb
#数据库配置（默认设置4个数据库）
e.db:
  driverClassName: com.mysql.cj.jdbc.Driver

mybatis.db:
  showSql: false
  globalConfig:
    metaObjectHandler: "cn.ezeyc.core.config.mybatis.ObjectHandler"
    configuration: #扩展配置（要与 Configuration 类的属性一一对应）
      cacheEnabled: false
      mapUnderscoreToCamelCase: true
    dbConfig:
      logicDeleteField: "remove"
      logicDeleteValue: "1"
#redis数据缓存默认配置
e.cache:
  keyHeader: "app"
  driverType: "redis" #驱动类型
  defSeconds: 3600 #默认为 30，可不配置
  db: 1 #默认为 0，可不配置
  password:
#token缓存
sa-token-dao: #名字可以随意取

#超时配置。单位秒（可不配，默认：7200）
server.session.timeout: 7200


# sa-token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 7200
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  allow-concurrent-login: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: tik
  # 是否输出操作日志
  is-log: true
  is-print: false
  #保存到redis
  redis:
    db: 0
    maxTotal: 2000
#配置加密
solon.vault:
  password: "wangze_991567775"
#分布式事件
solon.cloud.jedis:
  event:
    server: "localhost:6380"
    db: 5 #默认为 0，可不配置
    maxTotaol: 200 #默认为 200，可不配
  lock:
    server: "localhost:6380"
    db: 6 #默认为 0，可不配置
    maxTotaol: 200 #默认为 200，可不配
#健康监测
solon.health.detector: "*"